environment: ENC[AES256_GCM,data:AmbJ2l3q,iv:7rFoiPlTGSIC42mGQfi/YxsxgYRmhtXRyLjwjYRn7FA=,tag:mKPhIkDParFf0+gAJJlXJA==,type:str]
name: ENC[AES256_GCM,data:/hxFR114/neiW+ou2h1mGAlYHS8=,iv:AJqszCVY2XOSaSp/cq/gU/5dKlYoC5QYTI8faRu26RI=,tag:FYtad9qljtMLEb5wX01mUQ==,type:str]
port: ENC[AES256_GCM,data:ugj1cA==,iv:tfjTVQX5TMo9sqdkEKQ956Xb8ZDG2stncfOZL6b4Jg8=,tag:cbA+BCSF/GhEGSiisflLrQ==,type:int]
metrics: ENC[AES256_GCM,data:Jfm6tS8=,iv:0M6++EEnm+gjg5WbX1cPMTetKYPv0HIGtxaMKzNxih0=,tag:r6YNJ2NoGh9tiDBP9qYMHQ==,type:bool]
contracts:
    gameManagerAddress: ENC[AES256_GCM,data:K8oTme75YRJBh3AcANB6HPEy4dp2rhnOK3y3CNjqQCwbGuc+ncnCj7yP,iv:EWMcoeBNo67kwTJBUXueM+uegIA4MU2/MAoBJupP+gE=,tag:g/4I5MexJnd5SaH4gZnbWA==,type:str]
keys:
    admin: ENC[AES256_GCM,data:1UYLcNL/RW+NLQZvez28OD4EfwpUY9GIPT8MEIvx/5LLf5MUUt9VyVRciT6ynRn2Oyztt2b2e6poZH9PkdJaYQ==,iv:DzkdlphIxXRuaJSp5UWTh7o+srmZ43om3KfA+t+2zoU=,tag:1IhjvX5X3vF05G1uxL2MSQ==,type:str]
infura:
    url: ENC[AES256_GCM,data:lMvT/EwudAWWN6TvKndWMdtskLCE96LWcQ5Jx8k=,iv:9t3f3gnZpEoR5aaEhZZaKnB7hjIbpLaZRrz26fcFCPw=,tag:BxPCf0ZtO0ZLsjHxBp8a6A==,type:str]
    key: ENC[AES256_GCM,data:4RL9dkR5US920EUaOV5JxirrsIepqe+MWxc3shdFg9Q=,iv:pmRJkMUh+Dk/t7FHy/ZeGoZ9/bbyWu1O9SCP0jtEbmY=,tag:odq2e/Bl8++iItg65Utq9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-11-14T20:10:23Z'
    mac: ENC[AES256_GCM,data:5bnyKfdfXN+aHJZxtIV5qBaFmwwNEP0I4jDlIuNsyjajWaGpzPKV/ErogmedPrCWVeFe6xbw4RennXY8djKMY6/48tjO+E3Co+9G/HXl7z+0DBKhUUMqsQAaOH5QTh8qe91vsAFHi3xMXnKLZa44E0JMJs5OxMOahsloWJ1saig=,iv:9G4ldOH1qzju5N1T7HBGjGjs2IQZwFo1yxbElwsx2J0=,tag:tEZHIV20lvRvyOgKFKhMKw==,type:str]
    pgp:
    -   created_at: '2019-11-14T20:10:22Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAxcmV5QPlTskAQv+MebGKqVMb5JjWzn8S0swv/dNWqvA/ajYS1kCPsC0Wfw5
            tlXm0sEdRZH3COZujAJDxLGuM1uzwEm63YvgRM9JWp/MdnCR5r/HmmBuLuNP/iyl
            Ftkz98uUrReCAAWWopGBNPHpT/fK+zUTa5Tmm2i6St2/e/WekjP/JZfN2hGOGyVL
            2R+tMmDM9CuD4fk2TWQIm/WGzQEf8OTPtGRHTzzX8WEixvajtn8LunzsJx1rrHQR
            UvBTxTPW5A+4lXBLoVvnXq1tNR+7GA2I1KfF9r9t7KWl1Sa5M5WBVPojHEY1MraD
            ol0fyfWnSRgLAnUEr9Im/NhFWG0YLxkxeC4ef068/DBCacu08tBnH/Amx1rxhBdY
            BBk/mps9ndc3mylh4rGqfG8LSukBDUClzhge77/Yx1br99QLUdutjqkzpjkL2q/A
            XDw6qX5U6QGof8+CzteGhp963yr5tFQ5hoHmwUJLzuf0PaZSaVV+Yoi93TLqqVKX
            0qJIVi+xzmlb/JFTnrXm0l4BCluOw7OY5Oqr67sovZommRFDwKtuSXGoTcikxxsA
            qHvZ7FvDlmrCfTQLc16rOBJZfbNGXsha/kPGWGWolhutETfUi89gbh+G+7XFtvDN
            xy9nOg9Jq3t9dpW4wtYP
            =mdVB
            -----END PGP MESSAGE-----
        fp: 47C52A44009F2CDD681FEF9CF92E5E7AE9DCCB07
    unencrypted_suffix: _unencrypted
    version: 3.4.0
