openapi: 3.0.1
info:
  title: Game Jam Abstraction
  description: Game Jam Smart Contract Abstraction
  contact:
    email: support@bam.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
tags:
- name: game-jam-abstraction
  description: 
  externalDocs:
    description: Chain Abstraction Development Team
    url: http://chain-abstraction.dev
paths:
  /api/v1/health/status:
    get:
      tags:
      - game-jam-abstraction
      summary: Check the health of the service
      operationId: healthCheck
      responses:
        200:
          description: healthy response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Health'
        404:
          description: Not found
          content: {}
        401:
          description: Unauthorized
          content: {}
      security:
      - auth:
        - bam:access
  /api/v1/manager/get-all-gamejams:
    get:
      tags:
      - game-jam-abstraction
      summary: Get all active game jams
      operationId: getAllJams
      responses:
        200:
          description: healthy response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AllAddresses'
        404:
          description: Not found
          content: {}
        401:
          description: Unauthorized
          content: {}
      security:
      - auth:
        - bam:access
components:
  schemas:
    Health:
      type: object
      properties:
        message:
          type: string
          example: Healthy response from service at - 2019-10-28 01:15:49.392631014 +0000 GMT m=+72.576498242
        statusCode:
          type: number
          example: 200
    AllAddresses:
      type: object
      properties:
        addressList:
          type: string
          example: 0xA116c0dF8048741AAA9f6C46118faA92527b6221
        statusCode:
          type: number
          example: 200